apiVersion : apps/v1
kind: Deployment
metadata:
  name: bparinaspipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bparinaspipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: bparinaspipelinesjavascriptdocker 
    spec:
      containers:
        - name: bparinaspipelinesjavascriptdocker 
          image: prettywolf.azurecr.io/bparinaspipelinesjavascriptdocker
          ports:
          - containerPort: 8080